const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const page=await browser.newPage({reducedMotion:'reduce'});
 const requests=[], errors=[];
 page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8000/Unsere-Hochzeit.html');
 await page.locator('#open-text').click();await page.locator('#opening').waitFor({state:'hidden'});
 assert.equal(requests.length,1,'The standalone invitation must not fetch external resources.');
 assert(await page.locator('.garden-frame').evaluate(e=>e.complete&&e.naturalWidth>0));
 const calendarDownload=page.waitForEvent('download');await page.locator('#save-date').click();
 const calendar=fs.readFileSync(await (await calendarDownload).path(),'utf8');
 assert(calendar.includes('DTSTART:20270828T120000Z'),'14:00 Berlin in August must be 12:00 UTC.');
 await page.goto('http://localhost:8000/?edit=1');
 await page.getByRole('button',{name:'Einladung anpassen'}).click();
 const editor=page.locator('#editor-form');await editor.locator('[name="name1"]').fill('Marie');
 await editor.locator('[name="name2"]').fill('Simon');
 const htmlDownload=page.waitForEvent('download');await page.locator('#export-html').click();
 const html=fs.readFileSync(await (await htmlDownload).path(),'utf8');
 assert(html.includes('data:image/webp;base64,'));assert(html.includes('window.WEDDING'));
 const htmlPath='/tmp/verified-invitation-export.html';fs.writeFileSync(htmlPath,html);
 const offline=await browser.newPage({reducedMotion:'reduce'});const offlineRequests=[];
 offline.on('request',r=>offlineRequests.push(r.url()));await offline.route('http://localhost:8000/verified-export',route=>route.fulfill({body:html,contentType:'text/html'}));await offline.goto('http://localhost:8000/verified-export');
 await offline.locator('#open-text').click();await offline.locator('#opening').waitFor({state:'hidden'});
 assert.equal(offlineRequests.length,1,'An edited HTML export must also remain self-contained.');
 assert.deepEqual(errors,[]);await browser.close();
 process.stdout.write('Standalone HTML, edited export, image embedding and Berlin calendar time passed.\n');
})().catch(e=>{console.error(e);process.exit(1)});
